export const ANALYSIS_RESPONSE_SCHEMA = {
  type: "object",
  additionalProperties: false,
  properties: {
    isTargetValid: { type: "boolean" },
    riskLevel: { type: "string", enum: ["low", "moderate", "high", "emergency"] },
    confidence: { type: "string", enum: ["low", "medium", "high"] },
    summary: { type: "string" },
    possibleConditions: {
      type: "array",
      maxItems: 3,
      items: {
        type: "object",
        additionalProperties: false,
        properties: {
          name: { type: "string" },
          confidence: { type: "string", enum: ["low", "medium", "high"] },
          reason: { type: "string" },
          commonSymptoms: { type: "array", maxItems: 6, items: { type: "string" } },
        },
        required: ["name", "confidence", "reason", "commonSymptoms"],
      },
    },
    evidence: { type: "array", maxItems: 8, items: { type: "string" } },
    imageAssessment: { type: "string" },
    imageConsistency: {
      type: "object",
      additionalProperties: false,
      properties: {
        status: {
          type: "string",
          enum: [
            "not_provided",
            "match",
            "partial_match",
            "mismatch",
            "unclear",
            "not_evaluated",
          ],
        },
        explanation: { type: "string" },
        recommendedAction: { type: "string" },
      },
      required: ["status", "explanation", "recommendedAction"],
    },
    homeCare: { type: "array", maxItems: 8, items: { type: "string" } },
    dietPlan: {
      type: "object",
      additionalProperties: false,
      properties: {
        eat: { type: "array", maxItems: 8, items: { type: "string" } },
        avoid: { type: "array", maxItems: 8, items: { type: "string" } },
      },
      required: ["eat", "avoid"],
    },
    monitorSymptoms: { type: "array", maxItems: 8, items: { type: "string" } },
    redFlags: { type: "array", maxItems: 8, items: { type: "string" } },
    doctorRecommendation: {
      type: "object",
      additionalProperties: false,
      properties: {
        specialist: { type: "string" },
        timeframe: { type: "string" },
      },
      required: ["specialist", "timeframe"],
    },
    disclaimer: { type: "string" },
  },
  required: [
    "isTargetValid",
    "riskLevel",
    "confidence",
    "summary",
    "possibleConditions",
    "evidence",
    "imageAssessment",
    "imageConsistency",
    "homeCare",
    "dietPlan",
    "monitorSymptoms",
    "redFlags",
    "doctorRecommendation",
    "disclaimer",
  ],
};
