export const UI_COPY = {
  hi: {
    back: "पीछे",
    skip: "छोड़ें",
    next: "अगला",
    continue: "आगे बढ़ें",
    home: "होम",
    startInspection: "लक्षण जाँचें",
    previousInspections: "हाल की स्क्रीनिंग",
    noInspections: "आपकी पूरी की गई स्क्रीनिंग यहाँ दिखेगी।",
    privateAndSecure: "निजी और सुरक्षित",
    voiceEnabled: "हिंदी वॉइस",
    photoOptional: "फोटो वैकल्पिक",
    notDiagnosis: "यह निदान नहीं है",
    stepOne: "चरण 1 / 3",
    symptomCheck: "लक्षण जाँच",
    describeSymptoms: "आप कैसा महसूस कर रहे हैं?",
    describeSymptomsHint: "अपने मुख्य लक्षण, वे कब शुरू हुए और आपको कैसा महसूस हो रहा है—बताइए।",
    symptomPlaceholder: "जैसे: मुझे दो दिन से बुखार और सूखी खाँसी है…",
    speakSymptoms: "हिंदी या English में बोलने के लिए माइक दबाएँ",
    listening: "सुन रहा है… अब बोलिए",
    micUnavailable: "इस ब्राउज़र में वॉइस इनपुट उपलब्ध नहीं है। कृपया टाइप करें।",
    privateSession: "आपका जवाब इस स्क्रीनिंग सत्र में आपके डिवाइस पर रहता है।",
    redFlagFound: "तुरंत मदद की जरूरत हो सकती है",
    redFlagFoundHint: "आपने ऐसा लक्षण बताया है जिसकी ऑनलाइन स्क्रीनिंग में देरी नहीं करनी चाहिए।",
    getUrgentHelp: "तुरंत मदद देखें",
    emergencyEyebrow: "संभावित आपातस्थिति",
    emergencyTitle: "कृपया अभी चिकित्सा सहायता लें",
    emergencyBody: "इन लक्षणों के लिए ऑनलाइन परिणाम का इंतजार न करें। भारत में 112 पर कॉल करें या नज़दीकी आपातकालीन विभाग जाएँ।",
    callEmergency: "112 पर कॉल करें",
    emergencyNote: "यदि संभव हो तो अकेले न रहें और खुद गाड़ी न चलाएँ।",
    questionProgress: "सवाल",
    finishQuestions: "फोटो पर जाएँ",
    optionalPhoto: "वैकल्पिक फोटो",
    optionalPhotoTitle: "क्या लक्षण दिखाई देता है?",
    optionalPhotoHint: "त्वचा के दाने, सूजन, घाव या लालिमा के लिए फोटो मदद कर सकती है। फोटो जोड़ना जरूरी नहीं है।",
    openCamera: "कैमरा खोलें",
    gallery: "गैलरी से चुनें",
    cameraPermission: "कैमरा उपलब्ध नहीं है। अनुमति जाँचें या गैलरी से तस्वीर चुनें।",
    skipPhoto: "बिना फोटो आगे बढ़ें",
    finishPhotos: "फोटो पूरी—विश्लेषण करें",
    addAnother: "एक और फोटो जोड़ें",
    retake: "दोबारा लें",
    usePhoto: "यह फोटो रखें",
    photoPrivacy: "निजी अंगों की फोटो न लें। इस प्रोटोटाइप में फोटो आपके सत्र में ही रहती है।",
    analyzing: "आपकी जानकारी की समीक्षा हो रही है",
    analyzingHint: "हम संभावित स्थितियाँ और सुरक्षित अगला कदम तैयार कर रहे हैं।",
    demoHint: "प्रोटोटाइप मोड",
    retry: "दोबारा कोशिश करें",
    resultUnavailable: "परिणाम उपलब्ध नहीं है।",
    risk: "खतरे का स्तर",
    confidence: "विश्वास",
    low: "कम",
    moderate: "मध्यम",
    medium: "मध्यम",
    high: "अधिक",
    emergency: "आपातकाल",
    eat: "क्या लें",
    avoid: "क्या सीमित रखें",
    imageUsed: "फोटो समीक्षा",
    callNow: "112 पर कॉल करें",
    newInspection: "नई स्क्रीनिंग करें",
    possibleOnly: "संभावित स्थितियाँ—पुष्टि नहीं",
    switchToDark: "डार्क मोड चालू करें",
    switchToLight: "लाइट मोड चालू करें",
    symptomsLabel: "लक्षण",
    editSymptoms: "लक्षण संपादित करें",
    deleteSession: "स्क्रीनिंग हटाएं",
    clearAll: "सभी हटाएं",
    confirmDeleteSession: "क्या आप इस स्क्रीनिंग को इतिहास से हटाना चाहते हैं?",
    confirmClearAll: "क्या आप सारा स्क्रीनिंग इतिहास हटाना चाहते हैं?",
    aiHealthScreening: "एआई स्वास्थ्य स्क्रीनिंग",
    howAreYouFeeling: "आज आप कैसा महसूस कर रहे हैं?",
    howAreYouFeelingHint: "अपने लक्षण बोलें या लिखें। हम सुरक्षित अगला कदम समझने में मदद करेंगे।",
    view: "देखें",
    viewReport: "रिपोर्ट देखें",
    screeningSingular: "स्क्रीनिंग",
    screeningPlural: "स्क्रीनिंग",
    newScreeningTooltip: "नई स्वास्थ्य जाँच शुरू करें",
    healthCheckBadge: "एआई जाँच",
    safeGuidanceBadge: "सुरक्षित सलाह",
    symptomRequired: "कृपया आगे बढ़ने से पहले अपने लक्षण बताएं।",
    answerRequired: "कृपया आगे बढ़ने के लिए एक विकल्प चुनें।",
    listeningStatus: "सुन रहे हैं… अब बोलिए",
    processingSpeech: "आवाज़ प्रोसेस हो रही है…",
    speechSuccess: "आवाज़ दर्ज हो गई",
    speechError: "आवाज़ समझ नहीं आई। कृपया दोबारा बोलें या नीचे टाइप करें।",
    micPermissionDenied: "माइक्रोफ़ोन की अनुमति अस्वीकृत है।",
    micPermissionHint: "कृपया ब्राउज़र सेटिंग्स में माइक्रोफ़ोन की अनुमति दें या सीधे टाइप करें।",
    stepOneOfFour: "चरण 1 का 4: लक्षण",
    stepTwoOfFour: "चरण 2 का 4: सवाल",
    stepThreeOfFour: "चरण 3 का 4: फोटो",
    stepFourOfFour: "चरण 4 का 4: परिणाम",
    stageSymptoms: "लक्षणों का विश्लेषण किया जा रहा है…",
    stageAnswers: "नैदानिक संदर्भ और उत्तरों की समीक्षा हो रही है…",
    stageRecommendations: "सुरक्षित देखभाल और मार्गदर्शन तैयार हो रहा है…",
    analysisFailed: "जाँच पूरी नहीं हो सकी",
    analysisFailedDesc: "परिणाम तैयार करते समय कुछ समस्या आई। आपके लक्षण सुरक्षित हैं।",
    noScreeningsTitle: "अभी तक कोई स्क्रीनिंग नहीं",
    noScreeningsDesc: "आपकी पूरी की गई स्वास्थ्य जाँच यहाँ सुरक्षित रहेंगी ताकि आप कभी भी देख सकें।",
    startScreeningCta: "स्वास्थ्य जाँच शुरू करें",
    deleteModalTitle: "क्या यह स्क्रीनिंग हटाना चाहते हैं?",
    deleteModalDesc: "यह रिकॉर्ड हमेशा के लिए हटा दिया जाएगा। इसे वापस नहीं लाया जा सकता।",
    clearAllModalTitle: "सारा स्क्रीनिंग इतिहास हटाएं?",
    clearAllModalDesc: "आपकी सभी पुरानी स्क्रीनिंग हमेशा के लिए हटा दी जाएंगी। इसे वापस नहीं लाया जा सकता।",
    cancel: "रद्द करें",
    confirmDelete: "हटाएं",
    confirmClearAllBtn: "सभी हटाएं",
    resumeTitle: "जाँच प्रगति पर है",
    resumeDesc: "आपकी एक अधूरी स्वास्थ्य जाँच सुरक्षित है। क्या आप इसे जारी रखना चाहते हैं?",
    resumeBtn: "जाँच जारी रखें",
    startOverBtn: "नई जाँच शुरू करें",
    startNewConfirmTitle: "नई स्क्रीनिंग शुरू करें?",
    startNewConfirmDesc: "आपकी मौजूदा स्क्रीनिंग प्रगति मिट जाएगी। क्या आप वाकई नई जाँच शुरू करना चाहते हैं?",
    confirmStartNew: "हाँ, नई जाँच शुरू करें",
    offlineBannerTitle: "आप ऑफ़लाइन हैं",
    offlineBannerDesc: "नई AI स्क्रीनिंग के लिए इंटरनेट आवश्यक है। आपकी पुरानी स्क्रीनिंग अभी भी उपलब्ध हैं।",
    offlineAlert: "इंटरनेट कनेक्शन उपलब्ध नहीं है। कृपया कनेक्ट होने पर दोबारा प्रयास करें।",
    collapseSection: "छिपाएं",
    expandSection: "विस्तार से देखें",
    searchPlaceholder: "स्थिति या लक्षण से खोजें…",
    searchAriaLabel: "स्क्रीनिंग इतिहास में खोजें",
    filterBySeverity: "गंभीरता अनुसार फ़िल्टर",
    filterAll: "सभी",
    sortBy: "क्रमबद्ध करें",
    sortNewest: "नवीनतम पहले",
    sortOldest: "पुराने पहले",
    noSearchResultsTitle: "कोई मेल खाती स्क्रीनिंग नहीं मिली",
    noSearchResultsDesc: "अलग खोज शब्द का प्रयोग करें या फ़िल्टर हटाएँ।",
    clearFilters: "फ़िल्टर साफ़ करें",
    shareReport: "रिपोर्ट साझा करें",
    printReport: "प्रिंट करें",
    copySummary: "सारांश कॉपी करें",
    reportCopied: "रिपोर्ट सारांश क्लिपबोर्ड पर कॉपी हो गया",
    reportShared: "रिपोर्ट सफलतापूर्वक साझा की गई",
    shareNotSupported: "इस ब्राउज़र पर शेयरिंग समर्थित नहीं है। सारांश कॉपी कर दिया गया है।",
    historicalBadge: "पुरानी स्क्रीनिंग",
    screenedOn: "स्क्रीनिंग की तिथि",
    clinicalContextTitle: "आपके द्वारा दिए गए उत्तर",
    printDisclaimer: "यह सारांश केवल एआई-जनित प्राथमिक स्वास्थ्य जानकारी है, चिकित्सीय निदान नहीं। किसी भी रोग या लक्षण के लिए योग्य डॉक्टर से परामर्श लें।",
    cameraPermissionDenied: "कैमरे की अनुमति अस्वीकृत कर दी गई। कृपया ब्राउज़र सेटिंग्स में अनुमति दें या गैलरी से फ़ोटो चुनें।",
    cameraNotFound: "इस डिवाइस पर कोई कैमरा नहीं मिला। आप गैलरी से फ़ोटो चुन सकते हैं।",
    capturingImage: "फ़ोटो ली जा रही है…",
    processingImage: "छवि प्रोसेस हो रही है…",
    retryCamera: "कैमरा दोबारा आज़माएँ",
    errorBoundaryTitle: "कुछ गड़बड़ हो गई",
    errorBoundaryDesc: "एक अनपेक्षित त्रुटि हुई। आप होम स्क्रीन पर लौट सकते हैं या पेज रीलोड कर सकते हैं।",
    reloadApp: "पेज रीलोड करें",
    returnHome: "होम स्क्रीन पर जाएं",
    toastScreeningDeleted: "स्क्रीनिंग हटा दी गई",
    toastAllCleared: "सारा स्क्रीनिंग इतिहास हटा दिया गया",
  },
  en: {
    back: "Back",
    skip: "Skip",
    next: "Next",
    continue: "Continue",
    home: "Home",
    startInspection: "Check symptoms",
    previousInspections: "Recent screenings",
    noInspections: "Your completed screenings will appear here.",
    privateAndSecure: "Private by design",
    voiceEnabled: "Hindi voice",
    photoOptional: "Photo optional",
    notDiagnosis: "Not a diagnosis",
    stepOne: "Step 1 of 3",
    symptomCheck: "Symptom check",
    describeSymptoms: "How are you feeling?",
    describeSymptomsHint: "Describe your main symptoms, when they started, and how they are affecting you.",
    symptomPlaceholder: "For example: I have had a fever and dry cough for two days…",
    speakSymptoms: "Tap the mic to speak in Hindi or English",
    listening: "Listening… speak now",
    micUnavailable: "Voice input is unavailable in this browser. Please type instead.",
    privateSession: "Your response stays on your device for this screening session.",
    redFlagFound: "You may need urgent help",
    redFlagFoundHint: "You mentioned a symptom that should not be delayed for online screening.",
    getUrgentHelp: "See urgent guidance",
    emergencyEyebrow: "Possible emergency",
    emergencyTitle: "Please get medical help now",
    emergencyBody: "Do not wait for an online result. In India, call 112 or go to the nearest emergency department.",
    callEmergency: "Call 112",
    emergencyNote: "If possible, do not stay alone or drive yourself.",
    questionProgress: "Question",
    finishQuestions: "Continue to photo",
    optionalPhoto: "Optional photo",
    optionalPhotoTitle: "Is the symptom visible?",
    optionalPhotoHint: "A photo may help with a rash, swelling, wound, or redness. You do not have to add one.",
    openCamera: "Open camera",
    gallery: "Choose from gallery",
    cameraPermission: "Camera is unavailable. Check permission or choose an image from the gallery.",
    skipPhoto: "Continue without a photo",
    finishPhotos: "Finish photos and analyze",
    addAnother: "Add another photo",
    retake: "Retake",
    usePhoto: "Keep this photo",
    photoPrivacy: "Do not photograph intimate body areas. In this prototype, photos stay in your current session.",
    analyzing: "Reviewing your information",
    analyzingHint: "We are preparing possible conditions and safe next steps.",
    demoHint: "Prototype mode",
    retry: "Try again",
    resultUnavailable: "No result is available.",
    risk: "Urgency level",
    confidence: "Confidence",
    low: "Low",
    moderate: "Moderate",
    medium: "Medium",
    high: "High",
    emergency: "Emergency",
    eat: "Choose",
    avoid: "Limit",
    imageUsed: "Photo review",
    callNow: "Call 112",
    newInspection: "Start a new screening",
    possibleOnly: "Possible conditions—not confirmed",
    switchToDark: "Switch to dark mode",
    switchToLight: "Switch to light mode",
    symptomsLabel: "Symptoms",
    editSymptoms: "Edit symptoms",
    deleteSession: "Delete screening",
    clearAll: "Clear all",
    confirmDeleteSession: "Are you sure you want to delete this screening from history?",
    confirmClearAll: "Are you sure you want to clear all screening history?",
    aiHealthScreening: "AI HEALTH SCREENING",
    howAreYouFeeling: "How are you feeling today?",
    howAreYouFeelingHint: "Speak or type your symptoms. We’ll help you understand a safe next step.",
    view: "View",
    viewReport: "View report",
    screeningSingular: "screening",
    screeningPlural: "screenings",
    newScreeningTooltip: "Start new health screening",
    healthCheckBadge: "AI screening",
    safeGuidanceBadge: "Safe guidance",
    symptomRequired: "Please enter your symptoms before continuing.",
    answerRequired: "Please select an answer to continue.",
    listeningStatus: "Listening… speak now",
    processingSpeech: "Processing speech…",
    speechSuccess: "Speech recognized",
    speechError: "Could not recognize speech. Please speak again or type below.",
    micPermissionDenied: "Microphone permission was denied.",
    micPermissionHint: "Please allow microphone access in your browser settings, or type below.",
    stepOneOfFour: "Step 1 of 4: Symptoms",
    stepTwoOfFour: "Step 2 of 4: Questions",
    stepThreeOfFour: "Step 3 of 4: Photo",
    stepFourOfFour: "Step 4 of 4: Results",
    stageSymptoms: "Analyzing reported symptoms…",
    stageAnswers: "Reviewing contextual answers…",
    stageRecommendations: "Preparing safe care guidance…",
    analysisFailed: "Couldn't complete your screening",
    analysisFailedDesc: "Something went wrong while preparing your results. Your entered information is preserved.",
    noScreeningsTitle: "No screenings yet",
    noScreeningsDesc: "Your completed health screenings will appear here for easy reference anytime.",
    startScreeningCta: "Start a screening",
    deleteModalTitle: "Delete this screening?",
    deleteModalDesc: "This record will be permanently deleted and cannot be undone.",
    clearAllModalTitle: "Clear all screening history?",
    clearAllModalDesc: "All previous screening records will be permanently removed. This cannot be undone.",
    cancel: "Cancel",
    confirmDelete: "Delete",
    confirmClearAllBtn: "Clear all",
    resumeTitle: "Screening in progress",
    resumeDesc: "You have an unfinished screening session. Would you like to continue?",
    resumeBtn: "Resume screening",
    startOverBtn: "Start over",
    startNewConfirmTitle: "Start a new screening?",
    startNewConfirmDesc: "Your current screening progress will be lost. Are you sure you want to start over?",
    confirmStartNew: "Start new",
    offlineBannerTitle: "You're offline",
    offlineBannerDesc: "New AI screenings require an internet connection. Your existing screenings are still available.",
    offlineAlert: "Internet connection is unavailable. Please reconnect to start a new screening.",
    collapseSection: "Collapse",
    expandSection: "Expand",
    searchPlaceholder: "Search by condition or symptom…",
    searchAriaLabel: "Search screening history",
    filterBySeverity: "Filter by severity",
    filterAll: "All",
    sortBy: "Sort by",
    sortNewest: "Newest first",
    sortOldest: "Oldest first",
    noSearchResultsTitle: "No matching screenings found",
    noSearchResultsDesc: "Try adjusting your search terms or clearing your filters.",
    clearFilters: "Clear filters",
    shareReport: "Share report",
    printReport: "Print report",
    copySummary: "Copy summary",
    reportCopied: "Report summary copied to clipboard",
    reportShared: "Report shared successfully",
    shareNotSupported: "Web sharing is not supported on this browser. Summary copied instead.",
    historicalBadge: "Historical Screening",
    screenedOn: "Screened on",
    clinicalContextTitle: "Reported Consultation Context",
    printDisclaimer: "This summary is AI-generated health information and is not a medical diagnosis. For any clinical concerns, please consult a licensed healthcare professional.",
    cameraPermissionDenied: "Camera access was denied. Please allow camera permissions in your browser or choose a file from your gallery.",
    cameraNotFound: "No camera found on this device. You can choose a photo from your gallery instead.",
    capturingImage: "Capturing image…",
    processingImage: "Processing image…",
    retryCamera: "Retry camera",
    errorBoundaryTitle: "Something went wrong",
    errorBoundaryDesc: "An unexpected error occurred. You can return to the home screen or reload the application.",
    reloadApp: "Reload application",
    returnHome: "Return to Home",
    toastScreeningDeleted: "Screening deleted",
    toastAllCleared: "All screening history cleared",
  },
};

export function ui(language) {
  return UI_COPY[language] ?? UI_COPY.en;
}
