export const UI_COPY = {
  hi: {
    adaptiveQuestion: "आपके लक्षणों के अनुसार सवाल",
    preparingQuestions: "सवाल तैयार हो रहे हैं…",
    translatingReport: "रिपोर्ट का अनुवाद हो रहा है… कुछ क्षण रुकें।",
    translationUnavailable: "रिपोर्ट का अनुवाद अभी नहीं हो सका। पिछली भाषा में परिणाम दिखाए जा रहे हैं।",
    translationRateLimited: "AI की अनुरोध सीमा पूरी हो गई है। कुछ देर बाद भाषा बदलने का प्रयास करें।",
    translationProviderRejected: "AI ने अनुवाद अनुरोध अस्वीकार किया। सर्वर में मॉडल और API कुंजी की सेटिंग जाँचें।",
    caregiverTitle: "यह जाँच किसके लिए है?",
    caregiverHint: "अगर आप किसी और की मदद कर रहे हैं, तो उनका सही आयु वर्ग भी चुनें।",
    relation_self: "अपने लिए",
    relation_child: "बच्चे के लिए",
    relation_parent: "माता-पिता के लिए",
    relation_partner: "साथी के लिए",
    relation_other: "किसी और के लिए",
    safetyContextTitle: "दवाएँ और एलर्जी",
    safetyContextHint: "वैकल्पिक जानकारी; इसे केवल सुरक्षा संदर्भ के लिए उपयोग किया जाएगा। दवाएँ अपने आप न बदलें।",
    currentMedicines: "अभी ली जा रही दवाएँ",
    knownAllergies: "ज्ञात एलर्जी",
    optionalContextPlaceholder: "यदि पता हो तो लिखें (वैकल्पिक)",
    notProvided: "नहीं बताया गया",
    photoCheckTitle: "फोटो की जाँच",
    checkingPhoto: "फोटो और विवरण का मेल तथा गुणवत्ता देखी जा रही है…",
    photoCheckUnavailable: "अभी फोटो की जाँच उपलब्ध नहीं है; अंतिम स्क्रीनिंग में फोटो फिर जाँची जाएगी।",
    photoTooDark: "फोटो बहुत अंधेरी है। बेहतर रोशनी में दोबारा लें।",
    photoTooBlurry: "फोटो धुंधली लग रही है। कैमरा स्थिर रखकर फिर लें।",
    keepPhotoAnyway: "फिर भी फोटो रखें",
    savePdf: "प्रिंट / PDF सहेजें",
    readResults: "परिणाम सुनें",
    stopReading: "पढ़ना रोकें",
    unmuteToRead: "परिणाम सुनने के लिए आवाज़ चालू करें।",
    repeatScreening: "24–48 घंटों में फिर जाँचें",
    repeatScreeningSoon: "बाद में फिर जाँचें",
    progressTrackerTitle: "लक्षणों में बदलाव",
    reportedChange: "आपके उत्तरों के अनुसार बदलाव",
    trend_better: "बेहतर",
    trend_stable: "लगभग समान",
    trend_worse: "बदतर",
    progressComparisonHint: "यह आपके उत्तरों और फोटो की तुलना है; फोटो से स्वतः चिकित्सकीय बदलाव तय नहीं किया गया है।",
    previousCheck: "पिछली जाँच",
    currentCheck: "नई जाँच",
    followUpOf: "पिछली जाँच का अनुवर्ती",
    doctorReportTitle: "डॉक्टर के लिए स्क्रीनिंग रिपोर्ट",
    reportPatientContext: "रोगी की जानकारी",
    reportPhotoEvidence: "फोटो संदर्भ",
    reportAssessment: "स्क्रीनिंग अवलोकन",
    reportNextSteps: "अगले कदम और चेतावनियाँ",
    photoNotSaved: "इस जाँच की फोटो अब उपलब्ध नहीं है।",
    back: "पीछे",
    skip: "छोड़ें",
    next: "अगला",
    continue: "आगे बढ़ें",
    home: "होम",
    startInspection: "लक्षण जाँचें",
    previousInspections: "हाल की स्क्रीनिंग",
    noInspections: "आपकी पूरी की गई स्क्रीनिंग यहाँ दिखेगी।",
    privateAndSecure: "निजी और सुरक्षित",
    voiceEnabled: "हिंदी वॉइस",
    photoOptional: "फोटो वैकल्पिक",
    notDiagnosis: "यह निदान नहीं है",
    stepOne: "चरण 1 / 3",
    symptomCheck: "लक्षण जाँच",
    describeSymptoms: "आप कैसा महसूस कर रहे हैं?",
    describeSymptomsHint: "अपने मुख्य लक्षण, वे कब शुरू हुए और आपको कैसा महसूस हो रहा है—बताइए।",
    symptomPlaceholder: "जैसे: मुझे दो दिन से बुखार और सूखी खाँसी है…",
    speakSymptoms: "हिंदी या English में बोलने के लिए माइक दबाएँ",
    listening: "सुन रहा है… अब बोलिए",
    micUnavailable: "इस ब्राउज़र में वॉइस इनपुट उपलब्ध नहीं है। कृपया टाइप करें।",
    privateSession: "आगे बढ़ने पर आपके लक्षण एआई सेवा को अतिरिक्त सवाल चुनने के लिए भेजे जाएंगे।",
    redFlagFound: "तुरंत मदद की जरूरत हो सकती है",
    redFlagFoundHint: "आपने ऐसा लक्षण बताया है जिसकी ऑनलाइन स्क्रीनिंग में देरी नहीं करनी चाहिए।",
    getUrgentHelp: "तुरंत मदद देखें",
    emergencyEyebrow: "संभावित आपातस्थिति",
    emergencyTitle: "कृपया अभी चिकित्सा सहायता लें",
    emergencyBody: "इन लक्षणों के लिए ऑनलाइन परिणाम का इंतजार न करें। भारत में 112 पर कॉल करें या नज़दीकी आपातकालीन विभाग जाएँ।",
    callEmergency: "112 पर कॉल करें",
    emergencyNote: "यदि संभव हो तो अकेले न रहें और खुद गाड़ी न चलाएँ।",
    questionProgress: "सवाल",
    finishQuestions: "फोटो पर जाएँ",
    optionalPhoto: "वैकल्पिक फोटो",
    optionalPhotoTitle: "क्या लक्षण दिखाई देता है?",
    optionalPhotoHint: "त्वचा के दाने, सूजन, घाव या लालिमा के लिए फोटो मदद कर सकती है। फोटो जोड़ना जरूरी नहीं है।",
    openCamera: "कैमरा खोलें",
    gallery: "गैलरी से चुनें",
    cameraPermission: "कैमरा उपलब्ध नहीं है। अनुमति जाँचें या गैलरी से तस्वीर चुनें।",
    skipPhoto: "बिना फोटो आगे बढ़ें",
    finishPhotos: "फोटो पूरी—विश्लेषण करें",
    addAnother: "एक और फोटो जोड़ें",
    retake: "दोबारा लें",
    usePhoto: "यह फोटो रखें",
    photoPrivacy: "निजी अंगों की फोटो न लें। जाँच के लिए फोटो एआई सेवा को भेजी जाती है।",
    analyzing: "आपकी जानकारी की समीक्षा हो रही है",
    analyzingHint: "हम संभावित स्थितियाँ और सुरक्षित अगला कदम तैयार कर रहे हैं।",
    demoHint: "प्रोटोटाइप मोड",
    retry: "दोबारा कोशिश करें",
    resultUnavailable: "परिणाम उपलब्ध नहीं है।",
    risk: "खतरे का स्तर",
    confidence: "विश्वास",
    low: "कम",
    moderate: "मध्यम",
    medium: "मध्यम",
    high: "अधिक",
    emergency: "आपातकाल",
    eat: "क्या लें",
    avoid: "क्या सीमित रखें",
    imageUsed: "फोटो समीक्षा",
    imageConsistencyTitle: "फोटो और लक्षणों का मेल",
    imageStatus_not_provided: "फोटो नहीं दी गई",
    imageStatus_match: "विवरण से मेल",
    imageStatus_partial_match: "आंशिक मेल",
    imageStatus_mismatch: "विवरण से मेल नहीं",
    imageStatus_unclear: "फोटो अस्पष्ट है",
    imageStatus_not_evaluated: "फोटो की जाँच नहीं हुई",
    imageObserved: "फोटो में क्या दिखा",
    imageNextStep: "अगला कदम",
    callNow: "112 पर कॉल करें",
    newInspection: "नई स्क्रीनिंग करें",
    possibleOnly: "संभावित स्थितियाँ—पुष्टि नहीं",
    switchToDark: "डार्क मोड चालू करें",
    switchToLight: "लाइट मोड चालू करें",
    symptomsLabel: "लक्षण",
    editSymptoms: "लक्षण संपादित करें",
    deleteSession: "स्क्रीनिंग हटाएं",
    clearAll: "सभी हटाएं",
    confirmDeleteSession: "क्या आप इस स्क्रीनिंग को इतिहास से हटाना चाहते हैं?",
    confirmClearAll: "क्या आप सारा स्क्रीनिंग इतिहास हटाना चाहते हैं?",
    aiHealthScreening: "एआई स्वास्थ्य स्क्रीनिंग",
    howAreYouFeeling: "आज आप कैसा महसूस कर रहे हैं?",
    howAreYouFeelingHint: "अपने लक्षण बोलें या लिखें। हम सुरक्षित अगला कदम समझने में मदद करेंगे।",
    view: "देखें",
    viewReport: "रिपोर्ट देखें",
    screeningSingular: "स्क्रीनिंग",
    screeningPlural: "स्क्रीनिंग",
    newScreeningTooltip: "नई स्वास्थ्य जाँच शुरू करें",
    healthCheckBadge: "एआई जाँच",
    safeGuidanceBadge: "सुरक्षित सलाह",
    symptomRequired: "कृपया आगे बढ़ने से पहले अपने लक्षण बताएं।",
    answerRequired: "कृपया आगे बढ़ने के लिए एक विकल्प चुनें।",
    listeningStatus: "सुन रहे हैं… अब बोलिए",
    processingSpeech: "आवाज़ प्रोसेस हो रही है…",
    speechSuccess: "आवाज़ दर्ज हो गई",
    speechError: "आवाज़ समझ नहीं आई। कृपया दोबारा बोलें या नीचे टाइप करें।",
    micPermissionDenied: "माइक्रोफ़ोन की अनुमति अस्वीकृत है।",
    micPermissionHint: "कृपया ब्राउज़र सेटिंग्स में माइक्रोफ़ोन की अनुमति दें या सीधे टाइप करें।",
    stepOneOfFour: "चरण 1 का 4: लक्षण",
    stepTwoOfFour: "चरण 2 का 4: सवाल",
    stepThreeOfFour: "चरण 3 का 4: फोटो",
    stepFourOfFour: "चरण 4 का 4: परिणाम",
    stageSymptoms: "लक्षणों का विश्लेषण किया जा रहा है…",
    stageAnswers: "नैदानिक संदर्भ और उत्तरों की समीक्षा हो रही है…",
    stageRecommendations: "सुरक्षित देखभाल और मार्गदर्शन तैयार हो रहा है…",
    analysisFailed: "जाँच पूरी नहीं हो सकी",
    analysisFailedDesc: "परिणाम तैयार करते समय कुछ समस्या आई। आपके लक्षण सुरक्षित हैं।",
    aiNotConfigured: "AI स्क्रीनिंग सेवा अभी सेट नहीं है। कृपया ऐप सहायता से संपर्क करें।",
    aiInvalidKey: "AI सेवा का कनेक्शन अस्वीकृत हो गया। कृपया सर्वर की API सेटिंग जाँचें।",
    aiTimeout: "AI स्क्रीनिंग में बहुत समय लग रहा है। कृपया दोबारा कोशिश करें।",
    aiUnavailable: "AI स्क्रीनिंग सेवा तक अभी पहुँचा नहीं जा सका। कृपया कुछ देर बाद फिर कोशिश करें।",
    invalidScreening: "स्क्रीनिंग की जानकारी अधूरी या अमान्य है। कृपया अपने उत्तर जाँचें।",
    noScreeningsTitle: "अभी तक कोई स्क्रीनिंग नहीं",
    noScreeningsDesc: "आपकी पूरी की गई स्वास्थ्य जाँच यहाँ सुरक्षित रहेंगी ताकि आप कभी भी देख सकें।",
    startScreeningCta: "स्वास्थ्य जाँच शुरू करें",
    deleteModalTitle: "क्या यह स्क्रीनिंग हटाना चाहते हैं?",
    deleteModalDesc: "यह रिकॉर्ड हमेशा के लिए हटा दिया जाएगा। इसे वापस नहीं लाया जा सकता।",
    clearAllModalTitle: "सारा स्क्रीनिंग इतिहास हटाएं?",
    clearAllModalDesc: "आपकी सभी पुरानी स्क्रीनिंग हमेशा के लिए हटा दी जाएंगी। इसे वापस नहीं लाया जा सकता।",
    cancel: "रद्द करें",
    confirmDelete: "हटाएं",
    confirmClearAllBtn: "सभी हटाएं",
    resumeTitle: "जाँच प्रगति पर है",
    resumeDesc: "आपकी एक अधूरी स्वास्थ्य जाँच सुरक्षित है। क्या आप इसे जारी रखना चाहते हैं?",
    resumeBtn: "जाँच जारी रखें",
    startOverBtn: "नई जाँच शुरू करें",
    startNewConfirmTitle: "नई स्क्रीनिंग शुरू करें?",
    startNewConfirmDesc: "आपकी मौजूदा स्क्रीनिंग प्रगति मिट जाएगी। क्या आप वाकई नई जाँच शुरू करना चाहते हैं?",
    confirmStartNew: "हाँ, नई जाँच शुरू करें",
    offlineBannerTitle: "आप ऑफ़लाइन हैं",
    offlineBannerDesc: "नई AI स्क्रीनिंग के लिए इंटरनेट आवश्यक है। आपकी पुरानी स्क्रीनिंग अभी भी उपलब्ध हैं।",
    offlineAlert: "इंटरनेट कनेक्शन उपलब्ध नहीं है। कृपया कनेक्ट होने पर दोबारा प्रयास करें।",
    collapseSection: "छिपाएं",
    expandSection: "विस्तार से देखें",
    searchPlaceholder: "स्थिति या लक्षण से खोजें…",
    searchAriaLabel: "स्क्रीनिंग इतिहास में खोजें",
    filterBySeverity: "गंभीरता अनुसार फ़िल्टर",
    filterAll: "सभी",
    sortBy: "क्रमबद्ध करें",
    sortNewest: "नवीनतम पहले",
    sortOldest: "पुराने पहले",
    noSearchResultsTitle: "कोई मेल खाती स्क्रीनिंग नहीं मिली",
    noSearchResultsDesc: "अलग खोज शब्द का प्रयोग करें या फ़िल्टर हटाएँ।",
    clearFilters: "फ़िल्टर साफ़ करें",
    shareReport: "रिपोर्ट साझा करें",
    printReport: "प्रिंट करें",
    copySummary: "सारांश कॉपी करें",
    reportCopied: "रिपोर्ट सारांश क्लिपबोर्ड पर कॉपी हो गया",
    reportShared: "रिपोर्ट सफलतापूर्वक साझा की गई",
    shareNotSupported: "इस ब्राउज़र पर शेयरिंग समर्थित नहीं है। सारांश कॉपी कर दिया गया है।",
    historicalBadge: "पुरानी स्क्रीनिंग",
    screenedOn: "स्क्रीनिंग की तिथि",
    clinicalContextTitle: "आपके द्वारा दिए गए उत्तर",
    printDisclaimer: "यह सारांश केवल एआई-जनित प्राथमिक स्वास्थ्य जानकारी है, चिकित्सीय निदान नहीं। किसी भी रोग या लक्षण के लिए योग्य डॉक्टर से परामर्श लें।",
    cameraPermissionDenied: "कैमरे की अनुमति अस्वीकृत कर दी गई। कृपया ब्राउज़र सेटिंग्स में अनुमति दें या गैलरी से फ़ोटो चुनें।",
    cameraNotFound: "इस डिवाइस पर कोई कैमरा नहीं मिला। आप गैलरी से फ़ोटो चुन सकते हैं।",
    capturingImage: "फ़ोटो ली जा रही है…",
    processingImage: "छवि प्रोसेस हो रही है…",
    retryCamera: "कैमरा दोबारा आज़माएँ",
    errorBoundaryTitle: "कुछ गड़बड़ हो गई",
    errorBoundaryDesc: "एक अनपेक्षित त्रुटि हुई। आप होम स्क्रीन पर लौट सकते हैं या पेज रीलोड कर सकते हैं।",
    reloadApp: "पेज रीलोड करें",
    returnHome: "होम स्क्रीन पर जाएं",
    toastScreeningDeleted: "स्क्रीनिंग हटा दी गई",
    toastAllCleared: "सारा स्क्रीनिंग इतिहास हटा दिया गया",
    decisionSupportEyebrow: "एआई निर्णय सहायता और ट्रायज",
    decisionSupportDisclaimer: "निर्णय सहायता उपकरण · कोई चिकित्सकीय निदान उपकरण नहीं",
    workflowStep1Title: "1. लक्षण बताएं",
    workflowStep1Desc: "वॉइस या टेक्स्ट से आसानी से साझा करें",
    workflowStep2Title: "2. त्वरित सवाल",
    workflowStep2Desc: "अवधि और गंभीरता का स्पष्टीकरण",
    workflowStep3Title: "3. सुरक्षित मार्गदर्शन",
    workflowStep3Desc: "उचित स्तर, रेड फ्लैग और देखभाल टिप्स",
    homeInputMethodsNotice: "वॉइस या टेक्स्ट द्वारा दर्ज करें · फोटो पूरी तरह वैकल्पिक है",
    photoContextNotice: "तस्वीर केवल दृश्य संदर्भ के लिए है, किसी निश्चित चिकित्सकीय निदान के लिए नहीं।",
    dragDropPhoto: "यहाँ फोटो खींचकर छोड़ें या गैलरी से चुनें",
    dropToUpload: "अपलोड करने के लिए फ़ोटो यहाँ छोड़ें",
    removePhoto: "फोटो हटाएं",
    replacePhoto: "फोटो बदलें",
    reviewAndContinue: "समीक्षा और आगे बढ़ें",
    skipPhotoAndReview: "बिना फोटो समीक्षा पर जाएँ",
    reviewTitle: "स्क्रीनिंग समीक्षा",
    reviewSubtitle: "एआई विश्लेषण शुरू करने से पहले अपनी दर्ज की गई जानकारी जाँचें।",
    reviewStepLabel: "चरण 4 का 5: समीक्षा",
    startAnalysisCta: "एआई विश्लेषण शुरू करें",
    edit: "संपादित करें",
    reviewSymptomsSection: "दर्ज किए गए लक्षण",
    reviewQuestionsSection: "प्रश्न और अतिरिक्त उत्तर",
    reviewPhotoSection: "संलग्न फोटो संदर्भ",
    noPhotoAttached: "कोई फोटो नहीं जोड़ी गई (वैकल्पिक)",
    photoAttached: "फोटो संलग्न है",
    reviewPrivacyNotice: "लक्षण और वैकल्पिक फोटो पहले अतिरिक्त सवाल/फोटो जाँच के लिए एआई सेवा को भेजे जा सकते हैं। विश्लेषण में सभी उत्तर भेजे जाते हैं; पूरी रिपोर्ट इस डिवाइस पर सहेजी जाती है।",
    noSymptomsEntered: "कोई लक्षण दर्ज नहीं किए गए",
    returnHomeBtn: "होम स्क्रीन पर लौटें",
    newScreeningBtn: "नई स्क्रीनिंग शुरू करें",
    doctorConsultRecommendation: "अनुशंसित अगला कदम: डॉक्टर परामर्श",
    screeningStatsTitle: "स्क्रीनिंग गतिविधि और अवलोकन",
    totalScreeningsStat: "कुल स्क्रीनिंग",
    lowRiskStat: "कम गंभीरता",
    moderateRiskStat: "मध्यम गंभीरता",
    urgentRiskStat: "उच्च / आपातकालीन",
    photoAttachedStat: "फोटो संदर्भ सहित",
    lastScreenedStat: "नवीनतम स्क्रीनिंग",
    statsDisclaimer: "व्यक्तिगत स्क्रीनिंग रिकॉर्ड · केवल स्व-ट्रैकिंग के लिए, निरंतर स्वास्थ्य स्थिति या निदान का पैमाना नहीं।",
    emptyStatsTitle: "अभी कोई स्क्रीनिंग आँकड़े नहीं",
    emptyStatsDesc: "स्वास्थ्य जाँच पूरी करने पर आपकी गतिविधि के आँकड़े यहाँ प्रदर्शित होंगे।",
    whyThisResultTitle: "यह स्क्रीनिंग परिणाम क्यों?",
    whyThisResultSubtitle: "आपके बताए गए लक्षणों और नैदानिक संदर्भ ने इस मार्गदर्शन को कैसे प्रभावित किया",
    contributingFactors: "प्रमुख प्रासंगिक कारक",
    reportedSymptomsFactor: "बताए गए लक्षण",
    clinicalTimelineFactor: "अवधि और प्रभाव",
    visualContextFactor: "दृश्य संदर्भ (फोटो)",
    patternRationaleTitle: "पैटर्न मिलान और सुरक्षा तर्क",
    whyNextStepTitle: "अनुशंसित अगले कदम का आधार",
    whyResultNotice: "यह तर्क निर्णय सहायता दिशानिर्देशों और दर्ज लक्षणों पर आधारित है। यह कोई नैदानिक पुष्टि नहीं है।",
  },
  en: {
    adaptiveQuestion: "Question based on your symptoms",
    preparingQuestions: "Preparing questions…",
    translatingReport: "Translating your report… Please wait a moment.",
    translationUnavailable: "The report could not be translated right now. Results are shown in the previous language.",
    translationRateLimited: "The AI rate limit was reached. Please wait before switching languages again.",
    translationProviderRejected: "The AI provider rejected translation. Check the server's model and API key settings.",
    caregiverTitle: "Who is this screening for?",
    caregiverHint: "If you are helping someone else, choose their correct age group in the next step.",
    relation_self: "Myself",
    relation_child: "A child",
    relation_parent: "A parent",
    relation_partner: "A partner",
    relation_other: "Someone else",
    safetyContextTitle: "Medicines and allergies",
    safetyContextHint: "Optional details used only for safety context. Do not change medicines on your own.",
    currentMedicines: "Current medicines",
    knownAllergies: "Known allergies",
    optionalContextPlaceholder: "Enter details if known (optional)",
    notProvided: "Not provided",
    photoCheckTitle: "Photo check",
    checkingPhoto: "Checking photo quality and whether it matches your description…",
    photoCheckUnavailable: "The photo check is unavailable right now. The final screening will review the photo again.",
    photoTooDark: "The photo looks too dark. Try again in better light.",
    photoTooBlurry: "The photo looks blurry. Hold the camera steady and retake it.",
    keepPhotoAnyway: "Keep photo anyway",
    savePdf: "Print / Save PDF",
    readResults: "Read results aloud",
    stopReading: "Stop reading",
    unmuteToRead: "Turn sound on to hear the results.",
    repeatScreening: "Recheck in 24–48 hours",
    repeatScreeningSoon: "Check progress later",
    progressTrackerTitle: "Symptom progress",
    reportedChange: "Change based on your answers",
    trend_better: "Better",
    trend_stable: "About the same",
    trend_worse: "Worse",
    progressComparisonHint: "Your answers and photos are shown side by side. The photos are not used to automatically diagnose improvement.",
    previousCheck: "Previous check",
    currentCheck: "Current check",
    followUpOf: "Follow-up to",
    doctorReportTitle: "Screening report for a clinician",
    reportPatientContext: "Patient context",
    reportPhotoEvidence: "Photo context",
    reportAssessment: "Screening observations",
    reportNextSteps: "Next steps and warnings",
    photoNotSaved: "Photo no longer available for this screening.",
    back: "Back",
    skip: "Skip",
    next: "Next",
    continue: "Continue",
    home: "Home",
    startInspection: "Check symptoms",
    previousInspections: "Recent screenings",
    noInspections: "Your completed screenings will appear here.",
    privateAndSecure: "Private by design",
    voiceEnabled: "Hindi voice",
    photoOptional: "Photo optional",
    notDiagnosis: "Not a diagnosis",
    stepOne: "Step 1 of 3",
    symptomCheck: "Symptom check",
    describeSymptoms: "How are you feeling?",
    describeSymptomsHint: "Describe your main symptoms, when they started, and how they are affecting you.",
    symptomPlaceholder: "For example: I have had a fever and dry cough for two days…",
    speakSymptoms: "Tap the mic to speak in Hindi or English",
    listening: "Listening… speak now",
    micUnavailable: "Voice input is unavailable in this browser. Please type instead.",
    privateSession: "Continuing sends your symptoms to the AI service to select tailored questions.",
    redFlagFound: "You may need urgent help",
    redFlagFoundHint: "You mentioned a symptom that should not be delayed for online screening.",
    getUrgentHelp: "See urgent guidance",
    emergencyEyebrow: "Possible emergency",
    emergencyTitle: "Please get medical help now",
    emergencyBody: "Do not wait for an online result. In India, call 112 or go to the nearest emergency department.",
    callEmergency: "Call 112",
    emergencyNote: "If possible, do not stay alone or drive yourself.",
    questionProgress: "Question",
    finishQuestions: "Continue to photo",
    optionalPhoto: "Optional photo",
    optionalPhotoTitle: "Is the symptom visible?",
    optionalPhotoHint: "A photo may help with a rash, swelling, wound, or redness. You do not have to add one.",
    openCamera: "Open camera",
    gallery: "Choose from gallery",
    cameraPermission: "Camera is unavailable. Check permission or choose an image from the gallery.",
    skipPhoto: "Continue without a photo",
    finishPhotos: "Finish photos and analyze",
    addAnother: "Add another photo",
    retake: "Retake",
    usePhoto: "Keep this photo",
    photoPrivacy: "Do not photograph intimate body areas. Photos are sent to the AI service for checking and analysis.",
    analyzing: "Reviewing your information",
    analyzingHint: "We are preparing possible conditions and safe next steps.",
    demoHint: "Prototype mode",
    retry: "Try again",
    resultUnavailable: "No result is available.",
    risk: "Urgency level",
    confidence: "Confidence",
    low: "Low",
    moderate: "Moderate",
    medium: "Medium",
    high: "High",
    emergency: "Emergency",
    eat: "Choose",
    avoid: "Limit",
    imageUsed: "Photo review",
    imageConsistencyTitle: "Photo and symptom match",
    imageStatus_not_provided: "No photo provided",
    imageStatus_match: "Matches description",
    imageStatus_partial_match: "Partially matches",
    imageStatus_mismatch: "Does not match description",
    imageStatus_unclear: "Photo is unclear",
    imageStatus_not_evaluated: "Photo not evaluated",
    imageObserved: "What the photo shows",
    imageNextStep: "Next step",
    callNow: "Call 112",
    newInspection: "Start a new screening",
    possibleOnly: "Possible conditions—not confirmed",
    switchToDark: "Switch to dark mode",
    switchToLight: "Switch to light mode",
    symptomsLabel: "Symptoms",
    editSymptoms: "Edit symptoms",
    deleteSession: "Delete screening",
    clearAll: "Clear all",
    confirmDeleteSession: "Are you sure you want to delete this screening from history?",
    confirmClearAll: "Are you sure you want to clear all screening history?",
    aiHealthScreening: "AI HEALTH SCREENING",
    howAreYouFeeling: "How are you feeling today?",
    howAreYouFeelingHint: "Speak or type your symptoms. We’ll help you understand a safe next step.",
    view: "View",
    viewReport: "View report",
    screeningSingular: "screening",
    screeningPlural: "screenings",
    newScreeningTooltip: "Start new health screening",
    healthCheckBadge: "AI screening",
    safeGuidanceBadge: "Safe guidance",
    symptomRequired: "Please enter your symptoms before continuing.",
    answerRequired: "Please select an answer to continue.",
    listeningStatus: "Listening… speak now",
    processingSpeech: "Processing speech…",
    speechSuccess: "Speech recognized",
    speechError: "Could not recognize speech. Please speak again or type below.",
    micPermissionDenied: "Microphone permission was denied.",
    micPermissionHint: "Please allow microphone access in your browser settings, or type below.",
    stepOneOfFour: "Step 1 of 4: Symptoms",
    stepTwoOfFour: "Step 2 of 4: Questions",
    stepThreeOfFour: "Step 3 of 4: Photo",
    stepFourOfFour: "Step 4 of 4: Results",
    stageSymptoms: "Analyzing reported symptoms…",
    stageAnswers: "Reviewing contextual answers…",
    stageRecommendations: "Preparing safe care guidance…",
    analysisFailed: "Couldn't complete your screening",
    analysisFailedDesc: "Something went wrong while preparing your results. Your entered information is preserved.",
    aiNotConfigured: "The AI screening service is not configured yet. Please contact app support.",
    aiInvalidKey: "The AI service connection was rejected. Check the server API configuration.",
    aiTimeout: "The AI screening took too long. Please try again.",
    aiUnavailable: "The AI screening service cannot be reached right now. Please try again shortly.",
    invalidScreening: "The screening information is incomplete or invalid. Please review your answers.",
    noScreeningsTitle: "No screenings yet",
    noScreeningsDesc: "Your completed health screenings will appear here for easy reference anytime.",
    startScreeningCta: "Start a screening",
    deleteModalTitle: "Delete this screening?",
    deleteModalDesc: "This record will be permanently deleted and cannot be undone.",
    clearAllModalTitle: "Clear all screening history?",
    clearAllModalDesc: "All previous screening records will be permanently removed. This cannot be undone.",
    cancel: "Cancel",
    confirmDelete: "Delete",
    confirmClearAllBtn: "Clear all",
    resumeTitle: "Screening in progress",
    resumeDesc: "You have an unfinished screening session. Would you like to continue?",
    resumeBtn: "Resume screening",
    startOverBtn: "Start over",
    startNewConfirmTitle: "Start a new screening?",
    startNewConfirmDesc: "Your current screening progress will be lost. Are you sure you want to start over?",
    confirmStartNew: "Start new",
    offlineBannerTitle: "You're offline",
    offlineBannerDesc: "New AI screenings require an internet connection. Your existing screenings are still available.",
    offlineAlert: "Internet connection is unavailable. Please reconnect to start a new screening.",
    collapseSection: "Collapse",
    expandSection: "Expand",
    searchPlaceholder: "Search by condition or symptom…",
    searchAriaLabel: "Search screening history",
    filterBySeverity: "Filter by severity",
    filterAll: "All",
    sortBy: "Sort by",
    sortNewest: "Newest first",
    sortOldest: "Oldest first",
    noSearchResultsTitle: "No matching screenings found",
    noSearchResultsDesc: "Try adjusting your search terms or clearing your filters.",
    clearFilters: "Clear filters",
    shareReport: "Share report",
    printReport: "Print report",
    copySummary: "Copy summary",
    reportCopied: "Report summary copied to clipboard",
    reportShared: "Report shared successfully",
    shareNotSupported: "Web sharing is not supported on this browser. Summary copied instead.",
    historicalBadge: "Historical Screening",
    screenedOn: "Screened on",
    clinicalContextTitle: "Reported Consultation Context",
    printDisclaimer: "This summary is AI-generated health information and is not a medical diagnosis. For any clinical concerns, please consult a licensed healthcare professional.",
    cameraPermissionDenied: "Camera access was denied. Please allow camera permissions in your browser or choose a file from your gallery.",
    cameraNotFound: "No camera found on this device. You can choose a photo from your gallery instead.",
    capturingImage: "Capturing image…",
    processingImage: "Processing image…",
    retryCamera: "Retry camera",
    errorBoundaryTitle: "Something went wrong",
    errorBoundaryDesc: "An unexpected error occurred. You can return to the home screen or reload the application.",
    reloadApp: "Reload application",
    returnHome: "Return to Home",
    toastScreeningDeleted: "Screening deleted",
    toastAllCleared: "All screening history cleared",
    decisionSupportEyebrow: "AI Decision Support & Triage",
    decisionSupportDisclaimer: "Decision-support & triage tool · Not a diagnostic device",
    workflowStep1Title: "1. Describe symptoms",
    workflowStep1Desc: "Speak or type in Hindi or English",
    workflowStep2Title: "2. Quick questions",
    workflowStep2Desc: "Clarify timeline and severity",
    workflowStep3Title: "3. Safe guidance",
    workflowStep3Desc: "Urgency level, red flags & self-care",
    homeInputMethodsNotice: "Voice or text input · Photo strictly optional",
    photoContextNotice: "Photos provide visual context only, not a definitive medical diagnosis.",
    dragDropPhoto: "Drag & drop a photo here, or browse",
    dropToUpload: "Drop image to upload",
    removePhoto: "Remove photo",
    replacePhoto: "Replace photo",
    reviewAndContinue: "Review & continue",
    skipPhotoAndReview: "Continue without photo",
    reviewTitle: "Screening Review",
    reviewSubtitle: "Verify your entered information before starting AI analysis.",
    reviewStepLabel: "Step 4 of 5: Review",
    startAnalysisCta: "Start AI analysis",
    edit: "Edit",
    reviewSymptomsSection: "Reported symptoms",
    reviewQuestionsSection: "Questions and follow-ups",
    reviewPhotoSection: "Attached photo context",
    noPhotoAttached: "No photo attached (optional)",
    photoAttached: "Photo attached",
    reviewPrivacyNotice: "Symptoms and optional photos may already have been sent to the AI service for follow-up questions and photo checks. Analysis sends all answers; completed reports are saved on this device.",
    noSymptomsEntered: "No symptoms reported",
    returnHomeBtn: "Return to Home",
    newScreeningBtn: "Start a new screening",
    doctorConsultRecommendation: "Recommended Next Step: Doctor Consultation",
    screeningStatsTitle: "Screening Activity & Overview",
    totalScreeningsStat: "Total Screenings",
    lowRiskStat: "Low Urgency",
    moderateRiskStat: "Moderate Urgency",
    urgentRiskStat: "High / Urgent",
    photoAttachedStat: "With Photo Context",
    lastScreenedStat: "Latest screening",
    statsDisclaimer: "Personal screening log · For self-tracking only, not an indicator of ongoing health status or diagnostic progression.",
    emptyStatsTitle: "No screening statistics yet",
    emptyStatsDesc: "Activity metrics and outcome distributions will appear here as you complete screenings.",
    whyThisResultTitle: "Why this screening result?",
    whyThisResultSubtitle: "How your reported symptoms and clinical context contributed to this triage guidance",
    contributingFactors: "Key Contributing Factors",
    reportedSymptomsFactor: "Reported symptoms",
    clinicalTimelineFactor: "Timeline & impact",
    visualContextFactor: "Visual context",
    patternRationaleTitle: "Pattern Matching & Safety Rationale",
    whyNextStepTitle: "Basis for Recommended Next Step",
    whyResultNotice: "This rationale is generated using decision-support guidelines and reported symptoms. It is not a clinical diagnosis.",
  },
};

export function ui(language) {
  return UI_COPY[language] ?? UI_COPY.en;
}
