export const UI_COPY = {
  hi: {
    back: "पीछे",
    skip: "छोड़ें",
    next: "अगला",
    continue: "आगे बढ़ें",
    home: "होम",
    startInspection: "लक्षण जाँचें",
    previousInspections: "हाल की स्क्रीनिंग",
    noInspections: "आपकी पूरी की गई स्क्रीनिंग यहाँ दिखेगी।",
    privateAndSecure: "निजी और सुरक्षित",
    voiceEnabled: "हिंदी वॉइस",
    photoOptional: "फोटो वैकल्पिक",
    notDiagnosis: "यह निदान नहीं है",
    stepOne: "चरण 1 / 3",
    symptomCheck: "लक्षण जाँच",
    describeSymptoms: "आप कैसा महसूस कर रहे हैं?",
    describeSymptomsHint: "अपने मुख्य लक्षण, वे कब शुरू हुए और आपको कैसा महसूस हो रहा है—बताइए।",
    symptomPlaceholder: "जैसे: मुझे दो दिन से बुखार और सूखी खाँसी है…",
    speakSymptoms: "हिंदी या English में बोलने के लिए माइक दबाएँ",
    listening: "सुन रहा है… अब बोलिए",
    micUnavailable: "इस ब्राउज़र में वॉइस इनपुट उपलब्ध नहीं है। कृपया टाइप करें।",
    privateSession: "आपका जवाब इस स्क्रीनिंग सत्र में आपके डिवाइस पर रहता है।",
    redFlagFound: "तुरंत मदद की जरूरत हो सकती है",
    redFlagFoundHint: "आपने ऐसा लक्षण बताया है जिसकी ऑनलाइन स्क्रीनिंग में देरी नहीं करनी चाहिए।",
    getUrgentHelp: "तुरंत मदद देखें",
    emergencyEyebrow: "संभावित आपातस्थिति",
    emergencyTitle: "कृपया अभी चिकित्सा सहायता लें",
    emergencyBody: "इन लक्षणों के लिए ऑनलाइन परिणाम का इंतजार न करें। भारत में 112 पर कॉल करें या नज़दीकी आपातकालीन विभाग जाएँ।",
    callEmergency: "112 पर कॉल करें",
    emergencyNote: "यदि संभव हो तो अकेले न रहें और खुद गाड़ी न चलाएँ।",
    questionProgress: "सवाल",
    finishQuestions: "फोटो पर जाएँ",
    optionalPhoto: "वैकल्पिक फोटो",
    optionalPhotoTitle: "क्या लक्षण दिखाई देता है?",
    optionalPhotoHint: "त्वचा के दाने, सूजन, घाव या लालिमा के लिए फोटो मदद कर सकती है। फोटो जोड़ना जरूरी नहीं है।",
    openCamera: "कैमरा खोलें",
    gallery: "गैलरी से चुनें",
    cameraPermission: "कैमरा उपलब्ध नहीं है। अनुमति जाँचें या गैलरी से तस्वीर चुनें।",
    skipPhoto: "बिना फोटो आगे बढ़ें",
    finishPhotos: "फोटो पूरी—विश्लेषण करें",
    addAnother: "एक और फोटो जोड़ें",
    retake: "दोबारा लें",
    usePhoto: "यह फोटो रखें",
    photoPrivacy: "निजी अंगों की फोटो न लें। इस प्रोटोटाइप में फोटो आपके सत्र में ही रहती है।",
    analyzing: "आपकी जानकारी की समीक्षा हो रही है",
    analyzingHint: "हम संभावित स्थितियाँ और सुरक्षित अगला कदम तैयार कर रहे हैं।",
    demoHint: "प्रोटोटाइप मोड",
    retry: "दोबारा कोशिश करें",
    resultUnavailable: "परिणाम उपलब्ध नहीं है।",
    risk: "खतरे का स्तर",
    confidence: "विश्वास",
    low: "कम",
    moderate: "मध्यम",
    medium: "मध्यम",
    high: "अधिक",
    emergency: "आपातकाल",
    eat: "क्या लें",
    avoid: "क्या सीमित रखें",
    imageUsed: "फोटो समीक्षा",
    callNow: "112 पर कॉल करें",
    newInspection: "नई स्क्रीनिंग करें",
    possibleOnly: "संभावित स्थितियाँ—पुष्टि नहीं",
  },
  en: {
    back: "Back",
    skip: "Skip",
    next: "Next",
    continue: "Continue",
    home: "Home",
    startInspection: "Check symptoms",
    previousInspections: "Recent screenings",
    noInspections: "Your completed screenings will appear here.",
    privateAndSecure: "Private by design",
    voiceEnabled: "Hindi voice",
    photoOptional: "Photo optional",
    notDiagnosis: "Not a diagnosis",
    stepOne: "Step 1 of 3",
    symptomCheck: "Symptom check",
    describeSymptoms: "How are you feeling?",
    describeSymptomsHint: "Describe your main symptoms, when they started, and how they are affecting you.",
    symptomPlaceholder: "For example: I have had a fever and dry cough for two days…",
    speakSymptoms: "Tap the mic to speak in Hindi or English",
    listening: "Listening… speak now",
    micUnavailable: "Voice input is unavailable in this browser. Please type instead.",
    privateSession: "Your response stays on your device for this screening session.",
    redFlagFound: "You may need urgent help",
    redFlagFoundHint: "You mentioned a symptom that should not be delayed for online screening.",
    getUrgentHelp: "See urgent guidance",
    emergencyEyebrow: "Possible emergency",
    emergencyTitle: "Please get medical help now",
    emergencyBody: "Do not wait for an online result. In India, call 112 or go to the nearest emergency department.",
    callEmergency: "Call 112",
    emergencyNote: "If possible, do not stay alone or drive yourself.",
    questionProgress: "Question",
    finishQuestions: "Continue to photo",
    optionalPhoto: "Optional photo",
    optionalPhotoTitle: "Is the symptom visible?",
    optionalPhotoHint: "A photo may help with a rash, swelling, wound, or redness. You do not have to add one.",
    openCamera: "Open camera",
    gallery: "Choose from gallery",
    cameraPermission: "Camera is unavailable. Check permission or choose an image from the gallery.",
    skipPhoto: "Continue without a photo",
    finishPhotos: "Finish photos and analyze",
    addAnother: "Add another photo",
    retake: "Retake",
    usePhoto: "Keep this photo",
    photoPrivacy: "Do not photograph intimate body areas. In this prototype, photos stay in your current session.",
    analyzing: "Reviewing your information",
    analyzingHint: "We are preparing possible conditions and safe next steps.",
    demoHint: "Prototype mode",
    retry: "Try again",
    resultUnavailable: "No result is available.",
    risk: "Urgency level",
    confidence: "Confidence",
    low: "Low",
    moderate: "Moderate",
    medium: "Medium",
    high: "High",
    emergency: "Emergency",
    eat: "Choose",
    avoid: "Limit",
    imageUsed: "Photo review",
    callNow: "Call 112",
    newInspection: "Start a new screening",
    possibleOnly: "Possible conditions—not confirmed",
  },
};

export function ui(language) {
  return UI_COPY[language] ?? UI_COPY.en;
}
